### ISSUE TITLE
Save code and activity log

### ISSUE THREAD

**Issue by zerodevcuba** [tyron12233/CodeAssist#306] opened 2022-03-06 06:29 UTC
The application still hitting Save, deletes all my activity code. 

Bug 1:
![Screenshot_2022-03-06-01-25-32-399_com tyron code](https://user-images.githubusercontent.com/96848872/156912015-a9c6267a-e60f-41f8-897f-239aa210a878.jpg)

 - Device: Poco X3 Pro
 - OS: Android 11
 - Version: 0.2.8.2 ALPHA

**Comment by chengzhuangjie** [comment] 2022-03-06 09:16
I've encountered it too. I hope to repair it

**Comment by tyron12233** [comment] 2022-03-17 12:13
Duplicate of #229

**Closed by tyron12233** 2022-03-17 12:13 UTC
