### ISSUE TITLE
When i trying set ProgreBar style get error

### ISSUE THREAD

**Issue by LohitaMohanta** [tyron12233/CodeAssist#267] opened 2022-02-27 15:10 UTC
https://user-images.githubusercontent.com/100362821/155887861-110fd3f7-b420-4cd7-8a82-4c2934fca65c.mp4

**Comment by tyron12233** [comment] 2022-02-28 08:29
It would be helpful if you included what you have pasted on the attribute dialog. Can you share it here?

**Comment by LohitaMohanta** [comment] 2022-02-28 10:44
@style/Widget.Appcompat.ProgressBar.Horizontal

**Comment by LohitaMohanta** [comment] 2022-02-28 11:14
> It would be helpful if you included what you have pasted on the attribute dialog. Can you share it here?

`@style/Widget.Appcompat.ProgressBar.Horizontal`

**Comment by tyron12233** [comment] 2022-02-28 11:27
i just tried it and it doesn't seem to be related to the style of the progress bar. can you send the whole xml layout?

**Comment by LohitaMohanta** [comment] 2022-02-28 11:34
> i just tried it and it doesn't seem to be related to the style of the progress bar. can you send the whole xml layout?

`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
	tools:context=".RegisterActivity">
	
	<TextView
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:text="Register"
		android:textSize="26sp"
		android:textStyle="bold"
		android:layout_margin="32dp" />
		
		<LinearLayout
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:layout_centerInParent="true"
			android:padding="6dp"
			android:orientation="vertical">
			
			<EditText
				android:layout_weight="wrap_content"
				android:layout_height="wrap_content"
				android:padding="10dp"
				android:layout_marginTop="8dp"
				android:layout_marginBottom="8dp"
				android:hint="Name"
				android:id="@+id/nameET"
				android:inputType="text"
				android:background="@drawable/text_box"
				android:elevation="2dp" />
				
		    <EditText
				android:layout_weight="wrap_content"
				android:layout_height="wrap_content"
				android:padding="10dp"
				android:layout_marginTop="8dp"
				android:layout_marginBottom="8dp"
				android:hint="Email"
				android:id="@+id/emailET"
				android:inputType="textEmailAddress"
				android:background="@drawable/text_box"
				android:elevation="2dp" />
				
			<EditText
				android:layout_weight="wrap_content"
				android:layout_height="wrap_content"
				android:padding="10dp"
				android:layout_marginTop="8dp"
				android:layout_marginBottom="8dp"
				android:hint="Password"
				android:inputType="textPassword"
				android:id="@+id/passwordET"
				android:background="@drawable/text_box"
				android:elevation="2dp" />
				
			<EditText
                android:layout_weight="wrap_content"
                android:layout_height="wrap_content"
                android:padding="10dp"
                android:layout_marginTop="8dp"
                android:layout_marginBottom="8dp"
                android:hint="Confirm Password"
                android:id="@+id/confirmPass"
                android:background="@drawable/text_box"
                android:elevation="2dp" />
				
		</LinearLayout>
				
		<ProgressBar
			android:layout_width="wrap_content"
	    	android:layout_height="wrap_content"
	        android:layout_centerHorizontal="true"
			style="@style/Widget.Appcompat.ProgressBar.Horizontal"
			android:indeterminate="true"
		    android:visibility="visible"
			android:layout_margin="12dp"
			android:indeterminateTint="@color/blue"
			android:layout_above="@id/registerBtn" />
				
		<Button
		    android:layout_width="wrap_content"
	    	android:layout_height="wrap_content"
			android:id="@+id/registerBtn"
			android:layout_alignParentBottom="true"
			android:layout_margin="32dp"
			android:layout_centerHorizontal="true"
			android:minWidth="160dp"
			android:text="Register"
			android:textColor="@color/white"
			android:background="@drawable/btn" />
		
</RelativeLayout>`

**Comment by LohitaMohanta** [comment] 2022-02-28 11:37
> i just tried it and it doesn't seem to be related to the style of the progress bar. can you send the whole xml layout?

#

**Comment by tyron12233** [comment] 2022-02-28 11:37
Thats not a proper layout. Your layout code contains two roots (TextView and LinearLayout). There should only be one root, the feature is working as intended

**Comment by LohitaMohanta** [comment] 2022-02-28 11:38
> Thats not a proper layout. Your layout code contains two roots (TextView and LinearLayout). There should only be one root, the feature is working as intended

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
	tools:context=".RegisterActivity">
	
	<TextView
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:text="Register"
		android:textSize="26sp"
		android:textStyle="bold"
		android:layout_margin="32dp" />
		
		<LinearLayout
			android:layout_width="wrap_content"
			android:layout_height="wrap_content"
			android:layout_centerInParent="true"
			android:padding="6dp"
			android:orientation="vertical">
			
			<EditText
				android:layout_weight="wrap_content"
				android:layout_height="wrap_content"
				android:padding="10dp"
				android:layout_marginTop="8dp"
				android:layout_marginBottom="8dp"
				android:hint="Name"
				android:id="@+id/nameET"
				android:inputType="text"
				android:background="@drawable/text_box"
				android:elevation="2dp" />
				
		    <EditText
				android:layout_weight="wrap_content"
				android:layout_height="wrap_content"
				android:padding="10dp"
				android:layout_marginTop="8dp"
				android:layout_marginBottom="8dp"
				android:hint="Email"
				android:id="@+id/emailET"
				android:inputType="textEmailAddress"
				android:background="@drawable/text_box"
				android:elevation="2dp" />
				
			<EditText
				android:layout_weight="wrap_content"
				android:layout_height="wrap_content"
				android:padding="10dp"
				android:layout_marginTop="8dp"
				android:layout_marginBottom="8dp"
				android:hint="Password"
				android:inputType="textPassword"
				android:id="@+id/passwordET"
				android:background="@drawable/text_box"
				android:elevation="2dp" />
				
			<EditText
                android:layout_weight="wrap_content"
                android:layout_height="wrap_content"
                android:padding="10dp"
                android:layout_marginTop="8dp"
                android:layout_marginBottom="8dp"
                android:hint="Confirm Password"
                android:id="@+id/confirmPass"
                android:background="@drawable/text_box"
                android:elevation="2dp" />
				
		</LinearLayout>
				
		<ProgressBar
			android:layout_width="wrap_content"
	    	android:layout_height="wrap_content"
	        android:layout_centerHorizontal="true"
			style="@style/Widget.Appcompat.ProgressBar.Horizontal"
			android:indeterminate="true"
		    android:visibility="visible"
			android:layout_margin="12dp"
			android:indeterminateTint="@color/blue"
			android:layout_above="@id/registerBtn" />
				
		<Button
		    android:layout_width="wrap_content"
	    	android:layout_height="wrap_content"
			android:id="@+id/registerBtn"
			android:layout_alignParentBottom="true"
			android:layout_margin="32dp"
			android:layout_centerHorizontal="true"
			android:minWidth="160dp"
			android:text="Register"
			android:textColor="@color/white"
			android:background="@drawable/btn" />
		
</RelativeLayout>

**Comment by LohitaMohanta** [comment] 2022-02-28 11:41
> Thats not a proper layout. Your layout code contains two roots (TextView and LinearLayout). There should only be one root, the feature is working as intended

[Link](https://cdn.discordapp.com/attachments/920822555470880801/947820229235445810/activity_register.xml)

**Comment by tyron12233** [comment] 2022-02-28 11:44
You're missing the tools namespace on the root view. 

```
xmlns:tools="http://schemas.android.com/tools"
```

**Comment by LohitaMohanta** [comment] 2022-02-28 12:46
![Screenshot_2022-02-28-18-15-16-429_com tyron code](https://user-images.githubusercontent.com/100362821/155985764-1bb3ff5d-646f-4188-9c9a-cab4ad1ca187.jpg)

**Comment by tyron12233** [comment] 2022-03-01 04:16
This is no longer related to the issue that was originally posted, things are working as it should.

Please ask in the appropriate channels in the Disucssion tab, Discord server or telegram groups.

I will be closing this issue now

**Closed by tyron12233** 2022-03-01 04:16 UTC
