### ISSUE TITLE
This happen suddenly and all my codes that I've been working on the last 20mins before this crash are deleted (I've saved them and checked them well to be saved)

### ISSUE THREAD

**Issue by smith8h** [tyron12233/CodeAssist#245] opened 2022-02-20 15:47 UTC
Build version: 0.2.7 ALPHA 
Build date: 1981-01-01 01:01:02 
Current date: 2022-02-20 17:12:32 
Device: Xiaomi Redmi Note 6 Pro 
 
Stack trace:  
java.lang.IndexOutOfBoundsException
	at android.graphics.Paint.getTextRunAdvances(Paint.java:2277)
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureTextInner(GraphicTextRow.java:294)
	at io.github.rosemoe.sora.graphics.GraphicTextRow.measureTextInternal(GraphicTextRow.java:274)
	at io.github.rosemoe.sora.graphics.GraphicTextRow.buildMeasureCache(GraphicTextRow.java:111)
	at io.github.rosemoe.sora.widget.CodeEditor.buildMeasureCacheForLines(CodeEditor.java:1276)
	at io.github.rosemoe.sora.widget.CodeEditor.drawView(CodeEditor.java:1117)
	at io.github.rosemoe.sora.widget.CodeEditor.onDraw(CodeEditor.java:4506)
	at android.view.View.draw(View.java:20234)
	at android.view.View.updateDisplayListIfDirty(View.java:19109)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4321)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4294)
	at android.view.View.updateDisplayListIfDirty(View.java:19069)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3418)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3195)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2564)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1534)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7421)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
	at android.view.Choreographer.doCallbacks(Choreographer.java:888)
	at android.view.Choreographer.doFrame(Choreographer.java:819)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

User actions: 
2022-02-20 16:20:53: MainActivity created
2022-02-20 16:20:53: MainActivity resumed
2022-02-20 16:36:20: MainActivity paused
2022-02-20 16:36:21: MainActivity resumed
2022-02-20 16:47:45: MainActivity paused
2022-02-20 16:50:07: MainActivity resumed
2022-02-20 16:50:46: MainActivity paused
2022-02-20 16:51:24: MainActivity resumed
2022-02-20 16:51:43: MainActivity paused
2022-02-20 16:51:50: MainActivity resumed
2022-02-20 16:52:12: MainActivity paused
2022-02-20 16:52:19: MainActivity resumed
2022-02-20 16:52:36: MainActivity paused
2022-02-20 16:54:24: MainActivity resumed
2022-02-20 16:57:51: MainActivity paused
2022-02-20 16:58:08: MainActivity resumed
2022-02-20 17:02:13: MainActivity paused
2022-02-20 17:02:30: MainActivity resumed
2022-02-20 17:03:47: MainActivity paused
2022-02-20 17:04:18: MainActivity resumed
2022-02-20 17:05:58: MainActivity paused
2022-02-20 17:06:50: MainActivity resumed
2022-02-20 17:10:35: MainActivity paused
2022-02-20 17:11:10: MainActivity resumed

**Comment by tyron12233** [comment] 2022-03-17 12:13
Duplicate of #229

**Closed by tyron12233** 2022-03-17 12:13 UTC
