### ISSUE TITLE
NPE error

### ISSUE THREAD

**Issue by Hax4us** [tyron12233/CodeAssist#38] opened 2021-12-08 07:17 UTC
```
Build version: 1.0 
Build date: 1981-01-01 01:01:02 
Current date: 2021-12-08 12:46:12 
Device: Xiaomi Redmi Note 7 Pro 
 
Stack trace:  
java.lang.NullPointerException: Attempt to read from field 'org.openjdk.source.util.JavacTask com.tyron.completion.CompileBatch.task' on a null object reference
	at com.tyron.completion.JavaCompilerService.compile(JavaCompilerService.java:386)
	at com.tyron.completion.JavaCompilerService.compile(JavaCompilerService.java:372)
	at com.tyron.completion.provider.CompletionEngine.index(CompletionEngine.java:113)
	at com.tyron.ProjectManager.lambda$openProject$2$ProjectManager(ProjectManager.java:97)
	at com.tyron.ProjectManager$$ExternalSyntheticLambda6.run(Unknown Source:10)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

User actions: 
2021-12-08 12:45:59: MainActivity created
2021-12-08 12:45:59: MainActivity resumed
```

i just opened project for first time & it happened while resolving or indexing dependencies

**Comment by tyron12233** [comment] 2021-12-08 11:00
Is it a kotlin project?

**Comment by tyron12233** [comment] 2021-12-08 11:02
Seems to be a duplicate of #31, its fixed already thanks!

**Closed by tyron12233** 2021-12-08 11:02 UTC
