### ISSUE TITLE
Compiled Apps Doesn't Work

### ISSUE THREAD

**Issue by thewolfprod** [tyron12233/CodeAssist#65] opened 2021-12-17 16:18 UTC
Build version: 0.1.6 ALPHA
Device: Huawei SNE-LX1 (Android 10)

Compiled blank projects (AndroidX Template) do not work. The application compiles but when I open the application it closes immediately. There is no Error or App Logs in CodeAssist

Deleting App Data doesn't help.

Video:
https://streamable.com/cu9jy9

**Comment by gdb417** [comment] 2021-12-17 16:31
Some.

`Process: com.ert
PID: 20356
Flags: 0x30e8be44
Package: com.ert v1 (1.0)
Foreground: Yes
Build: Xiaomi/sagit/sagit:9/PKQ1.190118.001/V11.0.6.0.PCAMIXM:user/release-keys

java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/LifecycleEventObserver;
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1216)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2903)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3120)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1840)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.LifecycleEventObserver" on path: DexPathList[[zip file "/data/app/com.ert-AUPZHbEhMxCm77QJsg0V-w==/base.apk"],nativeLibraryDirectories=[/data/app/com.ert-AUPZHbEhMxCm77QJsg0V-w==/lib/arm64, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 16 more
`

**Comment by tyron12233** [comment] 2021-12-17 16:38
Thanks for this, theres been an issue with the jew dependency resolution it has been fixed with the latest commits

**Closed** 2021-12-17 16:39 UTC
