### ISSUE TITLE
Projects Path cleared when selecting cancel

### ISSUE THREAD

**Issue by NoOneCho** [tyron12233/CodeAssist#302] opened 2022-03-05 03:18 UTC
Device: Xiaomi Redmi 8
OS: MIUI 12 12.5.2 Stable
Version: 0.2.8.2 ALPHA

https://user-images.githubusercontent.com/100952177/156790653-b0dfec75-f502-4318-9b51-5f7f47998072.mp4

**Comment by tyron12233** [comment] 2022-03-14 12:07
Duplicate of #242

**Closed by tyron12233** 2022-03-14 12:07 UTC
Labels: duplicate
