### ISSUE TITLE
Fab button overlapping on Navigation Bar In CodeAssist V0.2.7 ALPHA

### ISSUE THREAD

**Issue by ArjunaKumarMohanta** [tyron12233/CodeAssist#239] opened 2022-02-18 23:30 UTC
![IMG_20220216_054750.jpg](https://user-images.githubusercontent.com/87923185/154774376-a5f5e8aa-c295-47b2-a150-c1cf7b433c4a.jpg)

**Comment by tyron12233** [comment] 2022-02-19 11:28
Duplicate of #222.

**Closed by tyron12233** 2022-02-19 11:28 UTC
Labels: duplicate
