### ISSUE TITLE
开启 自动换行首页代码错乱 点击格式化软件直接闪退崩溃

### ISSUE THREAD

**Issue by vip458** [tyron12233/CodeAssist#317] opened 2022-03-10 04:00 UTC
开启 自动换行首页代码错乱 点击格式化软件直接闪退崩溃
![Screenshot_2022-03-10-11-56-25-303_com tyron code](https://user-images.githubusercontent.com/59636798/157585766-d590f954-032c-4e08-9b38-4bc221f30d66.jpg)
![Screenshot_2022-03-10-11-54-30-683_com tyron code](https://user-images.githubusercontent.com/59636798/157585787-62ecaac6-6450-4125-9cf0-0952e400fc62.jpg)

**Comment by tyron12233** [comment] 2022-03-14 11:55
Please attach the error log (Can be copied by pressing the red button under the restart app button)

**Comment by tyron12233** [comment] 2022-03-14 12:10
Duplicate of #299 and is already fixed. Thanks

**Closed by tyron12233** 2022-03-14 12:10 UTC
Labels: Incomplete
